<?php
   //To Disable Cache Load if Browser Back Button Pressed
   use App\Http\Controllers\Enum\PlatformType;use App\Http\Controllers\functionController;
   use App\Http\Controllers\ActivitySession\functionController as activityFunctionController;
   use App\Http\Controllers\LoginRegister\functionController as loginFunctionController;
   header("Cache-Control: no-cache, no-store, must-revalidate"); // HTTP 1.1.
   header("Pragma: no-cache"); // HTTP 1.0.
   header("Expires: 0"); // Proxies.
   ?>
<?php
  if (Session::has('customer_id')) {
    $physical_address = (new loginFunctionController())->randomTextForLoginSession();
    (new activityFunctionController())->saveSession(session('customer_id'), PlatformType::web,
       $physical_address, $_SERVER['REMOTE_ADDR']);
  }
  $path = url()->current();
  $host = url('/');
  if (strpos($path, $host.'/partner-profile') !== false) {
      $is_profile = true;
  }
  $redirect_app_blog = false;
  $blog_heading = '';
  if(strpos($path, $host.'/blog') !== false){
      $blog_heading = isset($blog) ? $blog->heading : '';
      $redirect_app_blog = true;
  }
?>
<!DOCTYPE html>
<!--[if lt IE 7]>
<html lang="en" class="no-js lt-ie9 lt-ie8 lt-ie7">
   <![endif]-->
   <!--[if IE 7]>
   <html lang="en" class="no-js lt-ie9 lt-ie8">
      <![endif]-->
      <!--[if IE 8]>
      <html lang="en" class="no-js lt-ie9">
         <![endif]-->
         <!--[if gt IE 8]><!-->
         <html lang="en-us" class="no-js">
            <!--<![endif]-->
            <head>
               {{--hide body before loading all contents and show after loading--}}
               <style>.no-js {visibility: hidden;opacity: 0;}  .js {visibility: visible;opacity: 1;}</style>
               <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
               <script type="application/ld+json">
                  { "@context" : "http://schema.org", "@type" : "LocalBusiness", "name" : "Royalty", "image" : "https://s3-ap-southeast-1.amazonaws.com/royalty-bd/static-images/icon/rbd_logo_blue_beta.png", "telephone" : "+880-963-862-0202", "email" : "support@royaltybd.com", "address" : { "@type" : "PostalAddress", "streetAddress" : "Bashundhara Residential Area", "addressLocality" : "Dhaka", "postalCode" : "1229" },  "sameAs": [
                  "https://www.facebook.com/RoyaltyBD",
                  "https://twitter.com/RoyaltyBD",
                  "https://www.linkedin.com/company/royalty-bangladesh/"
                  ] }
               </script>
               <!-- Google Tag Manager -->
               <script>
                  (function(w, d, s, l, i) {
                      w[l] = w[l] || [];
                      w[l].push({
                          'gtm.start': new Date().getTime(),
                          event: 'gtm.js'
                      });
                      var f = d.getElementsByTagName(s)[0],
                          j = d.createElement(s),
                          dl = l != 'dataLayer' ? '&l=' + l : '';
                      j.async = true;
                      j.src =
                          'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
                      f.parentNode.insertBefore(j, f);
                  })(window, document, 'script', 'dataLayer', 'GTM-NGJZP84');
               </script>
               <!-- End Google Tag Manager -->
               @if(!isset($dont_redirect_mobile_page))
               <!-- <script>
                  function getMobileOperatingSystem(redirect_app_blog, blog_heading) {
                      var userAgent = navigator.userAgent || navigator.vendor || window.opera;
                  
                      if( userAgent.match( /iPad/i ) || userAgent.match( /iPhone/i ) || userAgent.match( /iPod/i ) ) {
                          if(redirect_app_blog){
                              window.location.href = '{{url('app-blog-single')}}'+'/'+blog_heading;
                          }
                          window.location.href = '{{url('royaltybdforphone')}}';
                      } else if( userAgent.match( /Android/i ) ) {
                          if(redirect_app_blog){
                              window.location.href = '{{url('app-blog-single')}}'+'/'+blog_heading;
                          }
                          window.location.href = '{{url('royaltybdforphone')}}';
                      }
                  }
                  getMobileOperatingSystem('{{$redirect_app_blog}}', '{{$blog_heading}}');
               </script> -->
               @endif
               <meta charset="UTF-8">
               <link rel="icon" href="https://s3-ap-southeast-1.amazonaws.com/royalty-bd/static-images/icon/top-logo-user.png">
               <title>{{$title ?? 'Royalty - Discover offers, discounts and rewards'}}</title>
               <meta name="csrf-token" content="{{ csrf_token() }}">
               @if(isset($singleReviewDetails['review']) && isset($singleReviewDetails['review']['id']))
               <?php
                  if($singleReviewDetails['review']['heading'] == null && $singleReviewDetails['review']['heading'] == 'n/a'){
                      $heading = '';
                  }else{
                      $heading = $singleReviewDetails['review']['heading'];
                  }
                  if($singleReviewDetails['review']['body'] == null && $singleReviewDetails['review']['body'] == 'n/a'){
                      $body = 'Rating '.$singleReviewDetails['review']['rating'];
                  }else{
                      $body = $singleReviewDetails['review']['body'];
                  }
                  ?>
               <meta property="fb:app_id" content="149014475722955">
               <meta property="og:url" content="{{$singleReviewDetails['review']['review_link']}}" />
               <meta property="og:type" content="website" />
               <meta property="og:title" content="{{$heading}}" />
               <meta property="og:description" content="{{$body}}" />
               <meta property="og:image" content="{{$singleReviewDetails['review']['partner_profile_image']}}" />
               @elseif(isset($singlePostDetails['post_details']) && isset($singlePostDetails['post_details']['id']))
               <?php
                  $heading = $singlePostDetails['post_details']['header'] == null ? '' : $singlePostDetails['post_details']['header'];
                  $caption = $singlePostDetails['post_details']['caption'] == null ? '' : $singlePostDetails['post_details']['caption'];
                  ?>
               <meta property="fb:app_id" content="149014475722955">
               <meta property="og:url" content="{{$singlePostDetails['post_details']['post_link']}}" />
               <meta property="og:type" content="website" />
               <meta property="og:title" content="{{$heading}}" />
               <meta property="og:description" content="{{$caption}}" />
               <meta property="og:image" content="{{$singlePostDetails['post_details']['image_url']}}" />
               @elseif(isset($is_profile) && $is_profile == true && isset($partnerInfo))
               <meta property="og:type" content="website" />
               <meta property="og:title" content="{{$title}}" />
               <meta property="og:image" content="{{$partnerInfo->profileImage->partner_profile_image}}" />
               @else
               <meta property="og:url" content="https://www.your-domain.com/your-page.html" />
               <meta property="og:type" content="website" />
               <meta property="og:title" content="Royalty" />
               <meta property="og:image" content="https://royalty-bd.s3-ap-southeast-1.amazonaws.com/static-images/icon/Royalty_logo.png" />
               @endif
               <meta property="fb:app_id" content="149014475722955">
               <meta name="viewport" content="width=device-width, initial-scale = 1.0, user-scalable = no">
               <meta name="description" content="{{$description ?? 'The first dedicated privilege platform in Bangladesh. Discover discounts & offers from hotels, restaurants, spas, salons and many more. Pay less, enjoy more!'}}">
               <meta name="keywords" content="health fitness, beauty spa, entertainment beauty, fitness getaways, spa health, entertainment beauty spa, health fitness getaways, spa health fitness, beauty spa health, drinks lifestyle entertainment, royalty, discount, offersbd, offersdhaka, privilege, loyaltycard, royaltycard, royaltycard, discountdhaka">
               <meta name="theme-color" content="#007bff">
               <link rel="canonical" href="{{url()->current()}}" />
               <script src="https://kit.fontawesome.com/9e60b11f48.js" crossorigin="anonymous" defer></script>
               <script src="https://js.pusher.com/5.0/pusher.min.js"></script>
               <link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet">
               <!-- Template Main CSS File -->
               <link href="{{asset('css/bootstrap.3.3.4.min.css')}}" rel="stylesheet">
                  <!-- Template Main MQ File -->
                 <link href="{{asset('css/mq.css')}}" rel="stylesheet">
                  <!-- Vendor CSS Files -->
                  <link href="{{asset('css/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
                  <link href="{{asset('css/stylenew.css')}}" rel="stylesheet">
                <link href="{{asset('css/icofont/icofont.min.css')}}" rel="stylesheet">
                <link href="{{asset('css/boxicons/css/boxicons.min.css')}}" rel="stylesheet">
                <link href="{{asset('css/venobox/venobox.css')}}" rel="stylesheet">
                <link href="{{asset('css/remixicon/remixicon.css')}}" rel="stylesheet">
                <link href="{{asset('css/aos/aos.css')}}" rel="stylesheet">
                <link rel="stylesheet" href="{{asset('css/devices.min.css')}}" type="text/css">
                <link rel="stylesheet" href="{{asset('css/owl.carousel.min.css')}}" type="text/css">
                <!-- Favicons -->
                <link href="https://royalty-bd.s3-ap-southeast-1.amazonaws.com/static-images/home-page/newimg/apple-touch-icon.png" rel="apple-touch-icon">
                <!-- Google Fonts -->
                <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Montserrat:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
               <style>
                  input[type="search"].searching::-webkit-input-placeholder {
                  color: gray;
                  opacity: .7;
                  }
                  #notification_ul{right: 0; left: auto;max-width:330px; min-width: 330px;min-height: 360px;max-height: 360px;}
                  #notification_ul .drop-content{min-height: 300px;max-height: 300px;overflow-y: scroll;overflow-x: hidden;}
                  #notification_ul li {background-color: unset; white-space: unset !important; float: left; width: 100%}
                  .unseen_notification {background-color: #e7e7e7 !important;}
               </style>
               <!-- Global site tag (gtag.js) - Google Analytics -->
               <script async src="https://www.googletagmanager.com/gtag/js?id=UA-111366305-1"></script>
               <script>
                  var host = window.location.hostname;
                  if(host === ('www.royaltybd.com' || 'royaltybd.com')) {
                      window.dataLayer = window.dataLayer || [];
                  
                      function gtag() {
                          dataLayer.push(arguments);
                      }
                      gtag('js', new Date());
                      gtag('config', 'UA-111366305-1');
                  }
               </script>
                <!-- mixpanel integration -->
                <script>(function(c,a){if(!a.__SV){var b=window;try{var d,m,j,k=b.location,f=k.hash;d=function(a,b){return(m=a.match(RegExp(b+"=([^&]*)")))?m[1]:null};f&&d(f,"state")&&(j=JSON.parse(decodeURIComponent(d(f,"state"))),"mpeditor"===j.action&&(b.sessionStorage.setItem("_mpcehash",f),history.replaceState(j.desiredHash||"",c.title,k.pathname+k.search)))}catch(n){}var l,h;window.mixpanel=a;a._i=[];a.init=function(b,d,g){function c(b,i){var a=i.split(".");2==a.length&&(b=b[a[0]],i=a[1]);b[i]=function(){b.push([i].concat(Array.prototype.slice.call(arguments,
                        0)))}}var e=a;"undefined"!==typeof g?e=a[g]=[]:g="mixpanel";e.people=e.people||[];e.toString=function(b){var a="mixpanel";"mixpanel"!==g&&(a+="."+g);b||(a+=" (stub)");return a};e.people.toString=function(){return e.toString(1)+".people (stub)"};l="disable time_event track track_pageview track_links track_forms track_with_groups add_group set_group remove_group register register_once alias unregister identify name_tag set_config reset opt_in_tracking opt_out_tracking has_opted_in_tracking has_opted_out_tracking clear_opt_in_out_tracking people.set people.set_once people.unset people.increment people.append people.union people.track_charge people.clear_charges people.delete_user people.remove".split(" ");
                        for(h=0;h<l.length;h++)c(e,l[h]);var f="set set_once union unset remove delete".split(" ");e.get_group=function(){function a(c){b[c]=function(){call2_args=arguments;call2=[c].concat(Array.prototype.slice.call(call2_args,0));e.push([d,call2])}}for(var b={},d=["get_group"].concat(Array.prototype.slice.call(arguments,0)),c=0;c<f.length;c++)a(f[c]);return b};a._i.push([b,d,g])};a.__SV=1.2;b=c.createElement("script");b.type="text/javascript";b.async=!0;b.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?
                        MIXPANEL_CUSTOM_LIB_URL:"file:"===c.location.protocol&&"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//)?"https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js":"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";d=c.getElementsByTagName("script")[0];d.parentNode.insertBefore(b,d)}})(document,window.mixpanel||[]);
                    mixpanel.init("9e0b1e7b656e8977256e114ee619a137", {batch_requests: true})</script>
            </head>
            <body>
               <noscript>
                  <meta HTTP-EQUIV="refresh" content=0;url="{{url('javascript-disabled')}}">
               </noscript>
               <!-- Google Tag Manager (noscript) -->
               <noscript>
                  <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NGJZP84" height="0" width="0" style="display:none;visibility:hidden"></iframe>
               </noscript>
               <!-- End Google Tag Manager (noscript) -->
               <?php $passChangeCount = (new functionController)->passChangeCount(); ?>
               @if(Session()->has('pass_change')) @if(Session()->get('pass_change') != $passChangeCount->pass_change)
               <script>
                  window.location = "{{ url('/customer_logout') }}";
               </script>
               @endif @endif
               <!-- Load Facebook SDK for JavaScript -->
               <div id="fb-root"></div>
               <script defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.3&appId=149014475722955&autoLogAppEvents=1"></script>
               {{--Navbar--}}
               <header id="header" class="fixed-top d-flex align-items-center">
               <div class="container d-flex align-items-center">
      <div class="logo mr-auto">
         <!-- <h1 class="text-light"><a href="index.html"><span>Bootslander</span></a></h1> -->
         <a href="{{url('/')}}"><img src="https://royalty-bd.s3-ap-southeast-1.amazonaws.com/static-images/icon/rbd_logo_blue.png" alt="Royalty Blue Logo" class="img-fluid"></a>
      </div>

       <form method="post" action="{{ url('/search-website') }}" id="small-search">
           @csrf
           <input type="search" placeholder="Search" name="search" id="small_searchname" autocomplete="off">
           <div id="small_txtHint" class="suggestion position-absolute"></div>
           <input type="submit" style="display: none;">
       </form>

      <nav class="nav-menu d-none d-lg-block">
         <ul>
            <!-- search -->
            <li>
               <form id="searchForm" method="post" action="{{ url('/search-website') }}" class="navbar-form search-bar">
                  <div class="frmSearch form-group">
                     <input type="hidden" name="_token" value="{{ csrf_token() }}">
                     <label for="searchname"></label>
                     <input placeholder="Search Brand or Area" type="search" class="searching form-control center"
                            id="searchname" name="search" autocomplete="off" style="width: 250px !important;">
                  </div>
                  <div id="txtHint" class="suggestion"></div>
                  <input type="submit" style="display: none;">
               </form>
            </li>
            <!-- HIW -->
{{--            <li>--}}
{{--               <a href="{{ url('how_it_works') }}">--}}
{{--                  <!-- <span><img src="https://s3-ap-southeast-1.amazonaws.com/royalty-bd/static-images/header/h2.png" alt="Royalty icon" class="header-icon"></span>  -->--}}
{{--                  How It Works--}}
{{--               </a>--}}
{{--            </li>--}}
{{--            <!-- Download -->--}}
{{--            <li class="drop-down">--}}
{{--               <a href="">Download App</a>--}}
{{--               <ul>--}}
{{--                  <li class="appqr-list">--}}
{{--                     <div class="h-qr-scan">--}}
{{--                        <img src="https://royalty-bd.s3-ap-southeast-1.amazonaws.com/static-images/all/appqr.png" width="100%" alt="Royalty App Download QR" />--}}
{{--                        <p class="header-app-download-text center">Scan to download</p>--}}
{{--                     </div>--}}
{{--                     <p class="header-app-download-text center">--}}
{{--                        <a href="http://bit.ly/RBDIOSAPP">IOS </a><a href="http://bit.ly/RBDANDROID"> Android</a>--}}
{{--                     </p>--}}
{{--                  </li>--}}
{{--               </ul>--}}
{{--            </li>--}}
            {{--When USER is not LOGGED IN --}}
            @if(!session()->has('customer_id'))
              @if(isset($page)){{--don't show login button--}}
              <li></li>
              @else
              <!-- login/signup -->
              <li>
                 <a href="{{url('login')}}">
                    <!-- <span><img src="https://s3-ap-southeast-1.amazonaws.com/royalty-bd/static-images/header/h3.png" alt="Royalty icon"  class="header-icon"></span> -->
                    <span class="nav_login">Login/Sign Up</span>
                 </a>
              </li>
              @endif
            {{--When USER is LOGGED IN--}}
            @elseif(session()->has('customer_id'))
              @if(isset($page))
              <li class="drop-down"></li>
              @else
              <li class="drop-down" id="customer_notifications">
                 <?php $allNotifications = Session::get('customerAllNotifications'); ?>
                 @if($allNotifications['total_notifications'] != 0)
                   <a href="#"><i class="bx bxs-bell"></i>
                   @if($allNotifications['unseen'] != 0)
                    <span class="notify_num" id="customer_notification_number">{{$allNotifications['unseen']}}</span>
                   @endif
                   </a>
                 <ul id="notification_ul">
                  <div class="drop-content">
                    <!-- Read all text -->
                    <li>
                       <p class="notification-header" style="float: left;">Your Notifications</p>
                       <a href="{{url('mark_user_all_notifications_as_read')}}" style="display: inline-block; float: right; font-size: 1.2rem">Read all</a>
                    </li>
                    <!-- Read all text ends -->
                    <!-- If customer has notif -->
                    @if(isset($allNotifications['today']) && count($allNotifications['today']) > 0)
                      <li><div class="notification-header">Today</div></li>
                      <?php
                       $notifications = (new functionController)->getNotificationView($allNotifications['today']);
                       echo $notifications;
                       ?>
                    @endif
                    @if(isset($allNotifications['yesterday']) && count($allNotifications['yesterday']) > 0)
                      <li><div class="notification-header">Yesterday</div></li>
                      <?php
                       $notifications = (new functionController)->getNotificationView($allNotifications['yesterday']);
                       echo $notifications;
                       ?>
                    @endif
                    @if(isset($allNotifications['this_week']) && count($allNotifications['this_week']) > 0)
                      <li><div class="notification-header">This week</div></li>
                      <?php
                       $notifications = (new functionController)->getNotificationView($allNotifications['this_week']);
                       echo $notifications;
                       ?>
                    @endif
                    @if(isset($allNotifications['earlier']) && count($allNotifications['earlier']) > 0)
                      <li><div class="notification-header">Earlier</div></li>
                      <?php
                       $notifications = (new functionController)->getNotificationView($allNotifications['earlier']);
                       echo $notifications;
                       ?>
                    @endif

                    </div>
                    <li>
                       <div class="notify-drop-footer text-center">
                          <a href="{{url('user/all-notifications')}}">View all notifications</a>
                       </div>
                    </li>
                 </ul>
                    <!-- If customer has notif ends -->
                    <!-- when customer doesn't have any notification -->
                    @else
                        <a href="#"><i class="bx bxs-bell"></i></a>
                        <ul id="notification_ul">
                        <div class="drop-content">
                          <li>
                             <p class="notification-header" style="float: left;">Your Notifications</p>
                          </li>
                             <p style="text-align: center;">You have no notifications</p>
                        </div>
                      </ul>
                    @endif
                  
              </li>
              {{-- User Name, Account, edit profile, logout dropdown--}}
              <li class="drop-down">
                 <a href="#"><i class='bx bxs-user-circle'></i></a>
                 <ul class="name-dropdown">
                    <li><a href="{{ url('/users/'.session('customer_username')) }}">Account</a></li>
                    <li><a href="{{ url('edit-profile') }}">Edit Profile</a></li>
                    <li><a href="#" onclick="customerLogout()">Logout</a></li>
                 </ul>
              </li>
              @endif
            @endif
         </ul>
      </nav>
   </div>
</header>